/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRequest {
  'id' : bigint,
  'service' : string,
  'contact' : string,
  'handled' : boolean,
  'name' : string,
  'createdAt' : Time,
  'message' : string,
  'preferredTime' : string,
}
export interface BusinessInfo {
  'tagline' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'openingHours' : Array<DayHours>,
  'phone' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface DayHours { 'hours' : string, 'days' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface GalleryImage {
  'id' : bigint,
  'url' : string,
  'caption' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface RevenueSummary {
  'completedCount' : bigint,
  'totalRevenue' : bigint,
  'counts' : StatusSummary,
}
export interface Service {
  'id' : bigint,
  'duration' : string,
  'name' : string,
  'description' : string,
  'price' : string,
}
export interface ServiceRequest {
  'id' : bigint,
  'service' : string,
  'status' : ServiceStatus,
  'contact' : string,
  'name' : string,
  'createdAt' : bigint,
  'complaint' : string,
  'deviceType' : string,
  'handoverTime' : string,
  'price' : bigint,
}
export interface ServiceRequestTracking {
  'id' : bigint,
  'service' : string,
  'status' : ServiceStatus,
  'deviceType' : string,
  'handoverTime' : string,
}
export type ServiceStatus = { 'Diterima' : null } |
  { 'Diambil' : null } |
  { 'Selesai' : null } |
  { 'Dikerjakan' : null };
export interface StatusSummary {
  'diterima' : bigint,
  'diambil' : bigint,
  'selesai' : bigint,
  'dikerjakan' : bigint,
}
export interface TeamMember {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'role' : string,
  'photo' : string,
}
export interface Testimonial {
  'id' : bigint,
  'quote' : string,
  'author' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__bookingRequests' : ActorMethod<[], any>,
  '__businessInfo' : ActorMethod<[], BusinessInfo>,
  '__gallery' : ActorMethod<[], Array<GalleryImage>>,
  '__nextRequestId' : ActorMethod<[], bigint>,
  '__serviceQueueState' : ActorMethod<[], any>,
  '__serviceRequests' : ActorMethod<[], any>,
  '__services' : ActorMethod<[], Array<Service>>,
  '__team' : ActorMethod<[], Array<TeamMember>>,
  '__testimonials' : ActorMethod<[], Array<Testimonial>>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBookingRequest' : ActorMethod<[bigint], undefined>,
  'deleteServiceRequest' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getBusinessInfo' : ActorMethod<[], BusinessInfo>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGallery' : ActorMethod<[], Array<GalleryImage>>,
  'getRevenueSummary' : ActorMethod<[], RevenueSummary>,
  'getServiceRequestStatusSummary' : ActorMethod<[], StatusSummary>,
  'getServiceRequestTracking' : ActorMethod<
    [bigint],
    [] | [ServiceRequestTracking]
  >,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getTeam' : ActorMethod<[], Array<TeamMember>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listBookingRequests' : ActorMethod<[], Array<BookingRequest>>,
  'listServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'schema' : ActorMethod<[], string>,
  'setBookingRequestHandled' : ActorMethod<[bigint, boolean], undefined>,
  'setServiceRequestStatus' : ActorMethod<[bigint, ServiceStatus], boolean>,
  'submitBookingRequest' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'submitServiceRequest' : ActorMethod<
    [string, string, string, string, string, string, bigint],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];