/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DayHours = IDL.Record({ 'hours' : IDL.Text, 'days' : IDL.Text });
export const BusinessInfo = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : IDL.Vec(DayHours),
  'phone' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'caption' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'photo' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'quote' : IDL.Text,
  'author' : IDL.Text,
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const StatusSummary = IDL.Record({
  'diterima' : IDL.Nat,
  'diambil' : IDL.Nat,
  'selesai' : IDL.Nat,
  'dikerjakan' : IDL.Nat,
});
export const RevenueSummary = IDL.Record({
  'completedCount' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'counts' : StatusSummary,
});
export const ServiceStatus = IDL.Variant({
  'Diterima' : IDL.Null,
  'Diambil' : IDL.Null,
  'Selesai' : IDL.Null,
  'Dikerjakan' : IDL.Null,
});
export const ServiceRequestTracking = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'status' : ServiceStatus,
  'deviceType' : IDL.Text,
  'handoverTime' : IDL.Text,
});
export const Time = IDL.Int;
export const BookingRequest = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'contact' : IDL.Text,
  'handled' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'message' : IDL.Text,
  'preferredTime' : IDL.Text,
});
export const ServiceRequest = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'status' : ServiceStatus,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'complaint' : IDL.Text,
  'deviceType' : IDL.Text,
  'handoverTime' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__bookingRequests' : IDL.Func([], [IDL.Reserved], ['query']),
  '__businessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  '__gallery' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  '__nextRequestId' : IDL.Func([], [IDL.Nat], ['query']),
  '__serviceQueueState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__serviceRequests' : IDL.Func([], [IDL.Reserved], ['query']),
  '__services' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  '__team' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  '__testimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBookingRequest' : IDL.Func([IDL.Nat], [], []),
  'deleteServiceRequest' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGallery' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getRevenueSummary' : IDL.Func([], [RevenueSummary], ['query']),
  'getServiceRequestStatusSummary' : IDL.Func([], [StatusSummary], ['query']),
  'getServiceRequestTracking' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ServiceRequestTracking)],
      ['query'],
    ),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getTeam' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listBookingRequests' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'listServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setBookingRequestHandled' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setServiceRequestStatus' : IDL.Func(
      [IDL.Nat, ServiceStatus],
      [IDL.Bool],
      [],
    ),
  'submitBookingRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitServiceRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DayHours = IDL.Record({ 'hours' : IDL.Text, 'days' : IDL.Text });
  const BusinessInfo = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : IDL.Vec(DayHours),
    'phone' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'caption' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'photo' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'quote' : IDL.Text,
    'author' : IDL.Text,
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const StatusSummary = IDL.Record({
    'diterima' : IDL.Nat,
    'diambil' : IDL.Nat,
    'selesai' : IDL.Nat,
    'dikerjakan' : IDL.Nat,
  });
  const RevenueSummary = IDL.Record({
    'completedCount' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'counts' : StatusSummary,
  });
  const ServiceStatus = IDL.Variant({
    'Diterima' : IDL.Null,
    'Diambil' : IDL.Null,
    'Selesai' : IDL.Null,
    'Dikerjakan' : IDL.Null,
  });
  const ServiceRequestTracking = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'status' : ServiceStatus,
    'deviceType' : IDL.Text,
    'handoverTime' : IDL.Text,
  });
  const Time = IDL.Int;
  const BookingRequest = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'contact' : IDL.Text,
    'handled' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'message' : IDL.Text,
    'preferredTime' : IDL.Text,
  });
  const ServiceRequest = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'status' : ServiceStatus,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'complaint' : IDL.Text,
    'deviceType' : IDL.Text,
    'handoverTime' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__bookingRequests' : IDL.Func([], [IDL.Reserved], ['query']),
    '__businessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    '__gallery' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    '__nextRequestId' : IDL.Func([], [IDL.Nat], ['query']),
    '__serviceQueueState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__serviceRequests' : IDL.Func([], [IDL.Reserved], ['query']),
    '__services' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    '__team' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    '__testimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBookingRequest' : IDL.Func([IDL.Nat], [], []),
    'deleteServiceRequest' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGallery' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getRevenueSummary' : IDL.Func([], [RevenueSummary], ['query']),
    'getServiceRequestStatusSummary' : IDL.Func([], [StatusSummary], ['query']),
    'getServiceRequestTracking' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ServiceRequestTracking)],
        ['query'],
      ),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getTeam' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listBookingRequests' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'listServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setBookingRequestHandled' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setServiceRequestStatus' : IDL.Func(
        [IDL.Nat, ServiceStatus],
        [IDL.Bool],
        [],
      ),
    'submitBookingRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitServiceRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };